DROP TABLE CHILD_STORE;

CREATE	EXTERNAL TABLE CHILD_STORE
( 
CHILD_STORE_ID INT  ,
CHILD_STORE_CD STRING  ,
CHILD_STORE_DESC STRING  ,
CHILD_STORE_MANAGER_NAME STRING  ,
CHILD_STORE_TYPE_ID INT  ,
CHILD_STORE_TYPE_CD STRING  ,
CHILD_STORE_TYPE_DESC STRING  ,
CHANNEL_ID INT  ,
CHANNEL_DESC STRING  
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION 's3n://mys3bucket/';
